# CircleCI 2.0 configuration file

version: 2
jobs:
  install:
    working_directory: ~/testing-circle-ci

    docker:
      # specify the version you desire here
      - image: circleci/node:8.5.0

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  build:
    docker:
      # specify the version here
      - image: circleci/node:8.5.0

      # run production build!
      - run: npm run build

      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
              - dist

workflows:
  version: 2
  install_and_build:
    jobs:
      - install
      - build:
          requires:
            - install
          filters:
            branches:
              only: master
